### ISSUE TITLE
java.lang.UnsatisfiedLinkError   couldn't find "libmp3lame.so"

### ISSUE THREAD

**Issue by Xiao1209** [zhaolewei/ZlwAudioRecorder#12]
引入 implementation 'com.github.zhaolewei:ZlwAudioRecorder:1.0.4'
运行 报
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kit.mp3-1/base.apk",...]] couldn't find "libmp3lame.so"`

**Comment by zhaolewei** [comment]
clean 下项目试试，我本地是可以运行的

**Comment by Xiao1209** [comment]
昨天我使用的是Android模拟器，所以报错。但是今天使用真机进行调用。可以正常运行。

**Comment by Xiao1209** [comment]
你好，我昨天使用的是Android模拟器进行的测试。出现了这样的报错。但是我今天使用两款真机，都无法正确使用。
Android4.4 报异常 couldn't find "libmp3lame.so"
Android7.0 报如下异常
`java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libmp3lame.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"`

RecordHelper 的日志输出如下：

- start...
- doStartRecording path: /data/user/0/x.x.x/cacherecord_20190408_11_10_00.mp3
- ----------------开始录制 MP3------------------------
- 参数： 录制格式： MP3,采样率：44100Hz,位宽：16 bit,声道数：2
- pcm缓存 tmpFile: /storage/emulated/0/Record/record_tmp_20190408_11_10_00.pcm
- 录音文件 resultFile: /data/user/0/x.x.x/cacherecord_20190408_11_10_00.mp3
- record buffer size = 7104
- in_sampleRate:44100，getChannelCount:2 ，out_sampleRate：44100 位宽： 16

两个机型在崩溃前RecordHelper的日志都是如此。

**Comment by zhaolewei** [comment]
降低targetSdkVersion 为26试下

**Comment by zhaolewei** [comment]
多编几个平台的库估计可以解决，晚上回去搞

**Comment by zhaolewei** [comment]
已更新
