### ISSUE TITLE
录制mp3的时候没有回调问题触发

### ISSUE THREAD

**Issue by kezhian** [zhaolewei/ZlwAudioRecorder#13]
录制MP3的时候，pause后stop没有回调，而且会把录音合并到上一次的录音里面

**Comment by zhaolewei** [comment]
Fix

**Comment by kezhian** [comment]
The problem is still unsolved.

**Comment by zj2050** [comment]
+1

**Comment by ferguschou** [comment]
mp3合并上一条解决方法：
1、在RecordHelper中对内部类AudioRecordThread构造方法加一个参数 isStart  ，如下：
 AudioRecordThread(boolean isStart) {
            bufferSize = AudioRecord.getMinBufferSize(currentConfig.getSampleRate(),
                    currentConfig.getChannelConfig(), currentConfig.getEncodingConfig()) * RECORD_AUDIO_BUFFER_TIMES;
            Logger.d(TAG, "record buffer size = %s", bufferSize);
            audioRecord = new AudioRecord(MediaRecorder.AudioSource.MIC, currentConfig.getSampleRate(),
                    currentConfig.getChannelConfig(), currentConfig.getEncodingConfig(), bufferSize);
            if (currentConfig.getFormat() == RecordConfig.RecordFormat.MP3) {
                if (mp3EncodeThread == null || isStart) {
                    initMp3EncoderThread(bufferSize);
                }
            }
        }

2、在RecordHelper的start() 中对应代码改为
audioRecordThread = new AudioRecordThread(true);
3、在RecordHelper的resume() 中对应代码改为
audioRecordThread = new AudioRecordThread(false);

测试了几个貌似好像没问题，不知是否会引发其他bug

**Comment by ferguschou** [comment]
回调问题解决：
在RecordHelper中makeFile()方法，
 将：
   case MP3:
       return;
改为：
  case MP3:
         break;
测试了几个完成状态 回调正常，不知是否会引发其他bug

**Comment by zhaolewei** [comment]
Fix : https://github.com/zhaolewei/ZlwAudioRecorder/commit/dbb25cee9d641fe8a9988450192643de6d9abf7a

感谢各位！
