### ISSUE TITLE
采集的音量db数太少。

### ISSUE THREAD

**Issue by VliceZ** [zhaolewei/ZlwAudioRecorder#16]
测试了一下，获取10个竟然需要700多毫秒，这样的话想做一个波形图很不平滑，有没有办法在同样的时间采集到更多的db数呢？

**Comment by VliceZ** [comment]
经测试startMp3Recorder 或startPcmRecorder方法里的while循环里有
int end = audioRecord.read(byteBuffer, 0, byteBuffer.length);
这句每执行一次大概耗费70~80ms，也就是说每获取一次dp都要从大量的byte数组数据中计算出音量大小需要70~80ms。这个应该是AudioRecord本身的问题。

**Comment by zhaolewei** [comment]
波形图需要平滑的话，建议在UI上优化，可以使用贝赛尔曲线进行绘制曲线来实现

**Comment by zhaolewei** [comment]
https://github.com/zhaolewei/MusicVisualizer
看下这个项目能不能帮到你

**Comment by zhaolewei** [comment]
https://github.com/zhaolewei/MusicVisualizer
看下这个项目能不能帮到你

**Comment by VliceZ** [comment]
我们这个比较特殊，UI的渲染是由我们这边将db数据采集到交由前端H5页面，前端的要求是数据尽可能多，但现在和理想比起来少态度，渲染出来的几乎成了一个折线  而不是波浪线。

**Comment by zhaolewei** [comment]
明白你的意思，但是无论是H5页面还是Android自定义控件，它都可以利用贝赛尔公式，将折线图转换成对应的曲线图

**Comment by VliceZ** [comment]
嗯，懂了，谢谢你的解答。
