### ISSUE TITLE
你好，我想要在计算音量分贝值时经过A计权和1/3倍频程的换算。请问大神有没有经验能指点一下，谢谢~

### ISSUE THREAD

**Issue by JQ-miao** [zhaolewei/ZlwAudioRecorder#18]

**Comment by zhaolewei** [comment]
计算分贝值的思路： 
1、 获取一端PCM数据，通过快速傅里叶变换（FFT）将其转换为频域数据
2、频域数据的大小为某段频率的振幅，求出振幅的平均值
3、根据公式：db = 20.0*log10(ave)可以算出声音大小
-------------------------------------------
想要获取低频段的声音大小，可将第二步做数据处理时删掉你不想要的频域数据，进行过滤即可。

**Comment by JQ-miao** [comment]
大神，recordManager.setRecordFftDataListener  这个监听是实时得到的FFT后的频域数据是吗？

**Comment by zhaolewei** [comment]
是
