### ISSUE TITLE
录音结束的时候会报异常java.io.IOException: Stream Closed

### ISSUE THREAD

**Issue by zpswz** [zhaolewei/ZlwAudioRecorder#21]
java.io.IOException: Stream Closed
在RecordHelper.java:505
关闭资源的时候把两个位置调换一下就可以了
try {
                if (fos != null) {
                    fos.close();
                }
                if (outputStream != null) {
                    outputStream.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
改成
try {
              if (outputStream != null) {
                    outputStream.close();
                }
                if (fos != null) {
                    fos.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
大佬可以把这个地方优化下

**Comment by zhaolewei** [comment]
Fix: https://github.com/zhaolewei/ZlwAudioRecorder/commit/45bdcfb62a39365b7d7a32c34f5dbd7f384f8bdb
