### ISSUE TITLE
stop方法调用问题

### ISSUE THREAD

**Issue by wangchang163** [zhaolewei/ZlwAudioRecorder#31]
感谢您的分享，我在测试的时候发现stop方法在调用的时候需要在pause的状态下才能执行，不然线程中会一直打印日志，所以建议在调用stop方法之前，先调用pause方法

**Comment by Dhy521** [comment]
你知道怎么重置吗 就是录一段时间没有保存 重新开始 怎么重置掉 释放 是哪个方法  我掉用stop还是会走保存逻辑

**Comment by zhaolewei** [comment]
录音文件在录制的时候已经存进去了，可以同过删除文件来释放

**Comment by zhaolewei** [comment]
@wangchang163  com.zlw.main.recorderlib.recorder.mp3.Mp3EncodeThread#stopSafe 在这里会在数据处理完成后才会停止
