### ISSUE TITLE
AudioView有些地方不懂，能给个联系方式请教一下吗？

### ISSUE THREAD

**Issue by oudengding** [zhaolewei/ZlwAudioRecorder#40]
AudioView有些地方不懂，能给个联系方式请教一下吗？

**Comment by xiaolanbuzaiaixinyi** [comment]
跪求。。。

**Comment by zhaolewei** [comment]
qq 739043667



---原始邮件---
发件人: "xiaolanbuzaiaixinyi"<notifications@github.com&gt;
发送时间: 2020年11月27日(周五) 下午4:02
收件人: "zhaolewei/ZlwAudioRecorder"<ZlwAudioRecorder@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [zhaolewei/ZlwAudioRecorder] AudioView有些地方不懂，能给个联系方式请教一下吗？ (#40)




 
跪求。。。
