### ISSUE TITLE
 急急急！！路过的大佬进来帮看看 跪谢跪谢..

### ISSUE THREAD

**Issue by Dhy521** [zhaolewei/ZlwAudioRecorder#43]
各位大佬 我遇到这个问题 删除录音文件 上一段录音还存在 
 
需求:有一个重置按钮 在录音中可以取消录音

然后我点击这个按钮 我去掉了.stop方法  log显示我 mp3EncodeThread is null, 代码业务流程有误，请检查！！这个错误是我没有进行初始化吗 但是我的日志是有初始化的阿
如果正常保存不会出现这个问题 错误

我看到有一个小伙伴提的问题和我这个差不多 我尝试了你说的 RecordManager.getInstance().stop();然后删除本地文件 我尝试了 没有作用的

这个是会缓存在内存中吗？如果缓存在内存中 是要清理内存吗

**Comment by zhaolewei** [comment]
Log “代码业务流程有误，请检查”  这个是因为mp3数据尚未处理完就 开始了下一次录音导致的。 可以在开始录音前，验证下录音状态。
