### ISSUE TITLE
可以修改文件名字吗

### ISSUE THREAD

**Issue by Mc-dashan** [zhaolewei/ZlwAudioRecorder#45]
可以修改文件得名字吗 不想使用默认得名字

**Comment by zhaolewei** [comment]
可以文件生成结束后重命名下

**Comment by Mc-dashan** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhaolewei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 下午5:32
收件人:&nbsp;"zhaolewei/ZlwAudioRecorder"<ZlwAudioRecorder@noreply.github.com&gt;;
抄送:&nbsp;"史贺"<936112399@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhaolewei/ZlwAudioRecorder] 可以修改文件名字吗 (#45)





 
可以文件生成结束后重命名下
