### ISSUE TITLE
录音时崩溃  大佬求解惑

### ISSUE THREAD

**Issue by MikeVoy** [zhaolewei/ZlwAudioRecorder#54]
java.lang.UnsatisfiedLinkError: No implementation found for void com.zlw.main.recorderlib.recorder.mp3.Mp3Encoder.init(int, int, int, int, int) (tried Java_com_zlw_main_recorderlib_recorder_mp3_Mp3Encoder_init and Java_com_zlw_main_recorderlib_recorder_mp3_Mp3Encoder_init__IIIII)  请问这种错需要我们使用者怎么做 是目录包名问题吗 ？so库相关的问题确实不懂

**Comment by zhaolewei** [comment]
so库与你的设备架构不符吧。是arm手机吗？
