### ISSUE TITLE
RecordHelper#AudioRecordThread#AudioRecord为什么不release呢？

### ISSUE THREAD

**Issue by huckings** [zhaolewei/ZlwAudioRecorder#63]
![image](https://user-images.githubusercontent.com/35586209/141282444-6b94aeeb-2f74-4bac-8cd9-3855cfedd28d.png)

这个对象为什么不release呢？

**Comment by zhaolewei** [comment]
还没研究过release，当时只stop了。这个框架是刚毕业时写的，感觉性能上还有很多问题，一直也没时间改。
